package web;

public enum FunctionType {
	TIME_SERIES_INTRADAY,
	TIME_SERIES_DAILY,
	TIME_SERIES_DAILY_ADJUSTED,
	TIME_SERIES_WEEKLY,
	TIME_SERIES_MONTHLY,
	TIME_SERIES_MONTHLY_ADJUSTED,
	GLOBAL_QUOTE,
	SYMBOL_SEARCH
}
